media: static/uploads
content:
  - name: config
    label: Config
    path: data/config.yaml
    type: file
    fields:
      - name: address
        label: Address
        type: string
      - name: phone
        label: Phone
        type: string
  - name: home
    label: Home
    path: content/_index.md
    type: file
    fields:
      - name: title
        label: Page title
        type: string
      - name: sections
        label: Sections
        type: list
        fields:
        - name: title
          label: Title
          type: string
        - name: content
          label: Content
          type: rich-text
  - name: about
    label: About
    path: content/about/_index.md
    type: file
    fields:
      - name: title
        label: Page title
        type: string
      - name: body
        label: Content
        type: rich-text
