# -----------------------------------------------------------------------------
# Media

media:
  input: static/media
  output: /media

# -----------------------------------------------------------------------------
# Content

content:

  # Home
  - name: home
    label: Home
    path: content/_index.md
    type: file
    fields:
      - name: title
        component: pageTitle
      - name: description
        component: pageDescription
      - name: params
        label: Page
        type: object
        fields:
          - name: pageHeader
            component: pageHeader
          - name: componentList
            component: componentList

  # Blog
  - name: blog
    label: Blog
    path: content/blog/_index.md
    type: file
    fields:
      - name: title
        component: pageTitle
      - name: description
        component: pageDescription
      - name: cascade
        label: All Pages
        type: object
        fields:
          - name: params
            label: Page
            type: object
            fields:
              - name: pageHeader
                component: pageHeader

  # Blog Posts
  - name: blogPosts
    label: Blog Posts
    type: collection
    path: content/blog
    exclude:
      - _index.md
    filename: "{fields.date}-{primary}.md"
    view:
      fields: [title, date, draft]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:00
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: body
        label: Content
        type: rich-text
      - name: tags
        label: Tags
        type: string
        list: true

  # Site Navigation
  - name: siteNavigation
    label: Site Navigation
    type: file
    path: config/_default/menu.yaml
    format: yaml
    fields:
      - name: main
        label: Main Menu
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "Menu Item #{index}"
        fields:
          - name: name
            label: Name
            type: string
            required: true
          - name: pageRef
            label: URL
            type: string
            required: true
          - name: weight
            label: Weight
            type: number

# -----------------------------------------------------------------------------
# Components

components:

  # Page Title
  pageTitle:
    label: Page Title
    type: string
    required: true

  # Page Description
  pageDescription:
    label: Page Description
    type: text
    options:
      rows: 3

  # Page Header
  pageHeader:
    label: Page Header
    type: object
    fields:
      - name: enabled
        label: Enabled
        type: boolean
        default: true
      - name: condensed
        label: Condensed
        type: boolean
        default: true
      - name: heading
        label: Heading
        type: string
      - name: subheading
        label: Subheading
        type: string

  # Accordion
  accordion:
    label: Accordion
    type: object
    fields:
      - name: exclusive
        label: Exclusive
        type: boolean
        default: true
      - name: details
        label: Details
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "Details #{index}"
        fields:
          - name: summary
            label: Summary
            type: string
          - name: content
            label: Content
            type: rich-text
          - name: open
            label: Open
            type: boolean
            default: false

  # Alert
  alert:
    label: Alert
    type: object
    fields:
      - name: variant
        label: Variant
        type: select
        required: true
        options:
          values: [ default, success, warning, error ]
      - name: content
        label: Content
        type: rich-text

  # Button
  button:
    label: Button
    type: object
    fields:
      - name: text
        label: Text
        type: string
      - name: url
        label: URL
        type: string
      - name: style
        label: Style
        type: select
        required: true
        options:
          values: [ default, outline, ghost ]
      - name: variant
        label: Variant
        type: select
        required: true
        options:
          values: [ default, primary, secondary, danger ]
      - name: size
        label: Size
        type: select
        required: true
        options:
          values: [ default, small, large ]

  # Card
  card:
    label: Card
    type: object
    fields:
      - name: heading
        label: Heading
        type: string
      - name: description
        label: Description
        type: string
      - name: content
        label: Content
        type: rich-text
      - name: footer
        label: Footer
        type: object
        list: true
        fields:
          - name: button
            component: button

  # Cards
  cards:
    label: Cards
    type: object
    fields:
      - name: cardlist
        label: Card List
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "Card #{index}"
        fields:
          - name: card
            component: card

  # Content
  content:
    label: Content
    type: object
    fields:
      - name: content
        label: Content
        type: rich-text

  # heading
  heading:
    label: Heading
    type: object
    fields:
      - name: level
        label: Level
        type: number
        required: true
        options:
          min: 1
          max: 6
          step: 1
      - name: text
        label: Text
        type: string

  # Tabs
  tabs:
    label: Tabs
    type: object
    fields:
      - name: tablist
        label: Tab List
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "Tab #{index}"
        fields:
          - name: tab
            label: Tab
            type: string
          - name: tabpanel
            label: Tab Panel
            type: rich-text

  # Component List
  componentList:
    label: Component List
    type: block
    list:
      collapsible:
        collapsed: true
        summary: "Component #{index}"
    blockKey: type
    blocks:
      - name: heading
        component: heading
      - name: content
        component: content
      - name: accordion
        component: accordion
      - name: alert
        component: alert
      - name: cards
        component: cards
      - name: tabs
        component: tabs
