media:
  input: static/media
  output: /media

content:

  # Home
  - name: home
    label: Home
    path: content/_index.md
    type: file
    fields:
      - name: title
        label: Title
        type: string
      - name: params
        label: Content
        type: object
        fields:
          - name: components
            component: components

  # About
  - name: about
    label: About
    path: content/about/_index.md
    type: file
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: body
        label: Content
        type: rich-text
      - name: aliases
        label: Aliases
        type: string
        list: true
        hidden: true

  # News
  - name: news
    label: News
    path: content/news/_index.md
    type: file
    fields:
      - name: title
        label: Title
        type: string
        required: true

  # News articles
  - name: articles
    label: News articles
    type: collection
    path: content/news
    exclude:
      - _index.md
    filename: "{fields.date}-{primary}.md"
    view:
      fields: [title, date, draft]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:00
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: body
        label: Content
        type: rich-text
      - name: tags
        label: Tags
        type: string
        list: true
        #type: select
        #options:
        #  creatable: true
        #  multiple: true
        #  fetch:
        # In a real-world use-case, this json file would be genereated at the root of the website and would contain all of the tags used the last time the site was built.
        #    url: https://raw.githubusercontent.com/squidfingers/pagescms-prototype/refs/heads/main/static/tags.json

  # Navigation
  - name: site-navigation
    label: Site Navigation
    type: file
    format: yaml
    path: config/_default/menu.yaml
    fields:
      - name: main
        label: Main Menu
        type: object
        list: true
        fields:
          - name: name
            label: Name
            type: string
            required: true
          - name: pageRef
            label: URL
            type: string
            required: true
          - name: weight
            label: Weight
            type: number

  # Site Settings
  - name: site-settings
    label: Site Settings
    type: file
    format: yaml
    path: config/_default/params.yaml
    fields:
      - name: address
        label: Address
        type: string
        required: true
      - name: phone
        label: Phone
        type: string
        required: true

  # Styles
  - name: user_styles
    label: Styles
    path: assets/css/styles.css
    type: file
    format: code

components:

  # Button
  button:
    label: Button
    type: object
    fields:
      - name: label
        label: Label
        type: string
      - name: link
        label: Link
        type: string
      - name: variant
        label: Variant
        type: select
        options:
          values: [primary, secondary]

  # Hero
  hero:
    label: Hero
    type: object
    fields:
      - name: title
        label: Title
        type: string
      - name: subtitle
        label: Subtitle
        type: string
      - name: cover
        label: Image
        type: image
        options:
          multiple: false

  # Cards
  cards:
    label: Cards
    type: object
    fields:
      - name: cards
        label: Cards
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "Card #{index}"
        fields:
          - name: title
            label: Title
            type: string
          - name: image
            label: Image
            type: image
            options:
              multiple: false
          - name: content
            label: Content
            type: rich-text
          - name: buttons
            label: Buttons
            list:
              collapsible:
                collapsed: true
                summary: "Button #{index}"
            component: button

  # Accordion
  accordion:
    label: Accordion
    type: object
    fields:
      - name: details
        label: Details
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "Detail #{index}"
        fields:
          - name: summary
            label: Summary
            type: string
          - name: content
            label: Content
            type: rich-text
            options:
              rows: 3

  # Page components
  components:
    label: Page Components
    type: block
    list:
      collapsible:
        collapsed: true
        summary: "Component #{index}"
    blockKey: type
    blocks:
      - name: accordion
        component: accordion
      - name: cards
        component: cards
      - name: hero
        component: hero
      - name: text
        label: Text
        fields:
          - name: content
            label: Content
            type: rich-text
