media: static/uploads
content:
  - name: config
    label: Config
    path: data/config.yaml
    type: file
    fields:
      - name: address
        label: Address
        type: string
      - name: phone
        label: Phone
        type: string
  - name: home
    label: Home
    path: content/_index.md
    type: file
    fields:
      - name: title
        label: Page title
        type: string
      - name: sections
        label: Sections
        type: object
        list: true
        fields:
        - name: title
          label: Title
          type: string
        - name: content
          label: Content
          type: rich-text
  - name: about
    label: About
    path: content/about/_index.md
    type: file
    fields:
      - name: title
        label: Page title
        type: string
      - name: body
        label: Content
        type: rich-text
  - name: news
    label: News
    path: content/news/_index.md
    type: file
    fields:
      - name: title
        label: Page title
        type: string
  - name: articles
    label: News articles
    type: collection
    path: content/news
    filename: '{year}-{month}-{day}-{primary}.md'
    view:
      fields: [ title, date, draft ]
      primary: title
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: body
        label: Content
        type: rich-text